on:
  push:
  pull_request:
  schedule:
  - cron: '0 6 * * 1'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: ./autogen.sh
    - run: ./configure
    - run: make all
    - run: nasm -v
    - run: python3 ./travis/nasm-t.py run
