on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: sh autogen.sh
    - run: sh configure
    - run: make
    - run: make strip
    - run: make install
